[workspace]
members = [
  "src/base",
  "src/chillerbot-rs",
  "src/engine",
  "src/engine/shared",
  "src/rust-bridge/test",
]

[profile.dev]
panic = "abort"

[profile.release]
lto = "thin"
panic = "abort"

